### ISSUE TITLE
u forgot to git pull before releasing

### ISSUE THREAD

**Issue by Tecnio** [zajchu1337/rise#1]
before downloading the src u should have ran `git pull` therefore u would have the other commits as well

**Comment by OfficialError** [comment]
😢

**Comment by devteqhs** [comment]
👽

**Comment by dev-vince** [comment]
> before downloading the src u should have ran `git pull` therefore u would have the other commits as well

did these said commits fix the static abuse?
vince code isn't even this bad anymore 😭

**Comment by JohnKiernsPizzaMan** [comment]
Vince's code somehow is better than this horrific mess. Please recode

**Comment by opZywl** [comment]
⛷
