### ISSUE TITLE
the net/minecraft folder is not there :(

### ISSUE THREAD

**Issue by 24McNuggets** [zajchu1337/rise#4]
If possible, would it be possible you could:
 - Provide the net/minecraft and other respective folders (assets, viaversion, libraries, etc)
 - Rise 5.100 with the things above

Thanks,

\- 24McNuggets :smile:

**Comment by RealPacket** [comment]
I'll try to get the right version and make a fork if I can

**Comment by zajchu1337** [comment]
nah im good

**Comment by RealPacket** [comment]
> nah im good

took long enough for you to respond...
